server:
  port: 8085
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Mzy001007

  devtools: #热部署
    livereload:
      enabled: true

  jackson:
    time-zone: GMT+8
    date-format: YYYY-MM-DD HH:mm:ss

mybatis-plus:
  type-aliases-package: com.markmzy.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:dao/*.xml




